// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package gui

import "fyne.io/fyne/v2"

var resourceAppIconSvg = &fyne.StaticResource{
	StaticName: "gemini-svg.svg",
	StaticContent: []byte(
		"<svg width=\"32\" height=\"32\" viewBox=\"0 0 32 32\" xmlns=\"http://www.w3.org/2000/svg\">\n  <rect width=\"32\" height=\"32\" rx=\"6\" fill=\"#00E5FF\"/>\n  \n  <path d=\"M8 10 L16 22 L24 10\" fill=\"none\" stroke=\"#1A1B2E\" stroke-width=\"4\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>\n  <circle cx=\"16\" cy=\"12\" r=\"3\" fill=\"#1A1B2E\"/>\n</svg>\n"),
}
