// Package secret provides domain types for the passwd secrets manager.
// It is a pure domain types package — depends on nothing in the project.
package secret

import (
	"encoding/json"
	"time"
)

// Kind represents the type of a secret.
type Kind string

const (
	KindPassword    Kind = "password"
	KindAPIKey      Kind = "api_key"
	KindCertificate Kind = "certificate"
	KindSSHKey      Kind = "ssh_key"
	KindNote        Kind = "note"
	KindOther       Kind = "other"
)

// ValidKinds returns all valid secret kinds.
func ValidKinds() []Kind {
	return []Kind{
		KindPassword,
		KindAPIKey,
		KindCertificate,
		KindSSHKey,
		KindNote,
		KindOther,
	}
}

// IsValidKind checks if a kind string is a valid secret kind.
func IsValidKind(k string) bool {
	switch Kind(k) {
	case KindPassword, KindAPIKey, KindCertificate, KindSSHKey, KindNote, KindOther:
		return true
	default:
		return false
	}
}

// Secret represents an encrypted secret stored in the vault.
// EncryptedValue is ALWAYS ciphertext — never plaintext.
//
// Schema v7 (hardening-and-breach-alerts) stores all metadata as ciphertext
// BLOBs. The Name, Notes, Tags, and Metadata fields hold decrypted plaintext
// in-memory only; the Store layer persists the Encrypted* counterparts and the
// NameLookup HMAC. The App layer is responsible for encryption before Store
// and decryption after Load.
//
// EncryptedOTPSeed (added with schema v5 for issue S-02) holds the TOTP/HOTP
// `secret=` parameter, wrapped with the master key. It is nil for secrets
// without an OTP component.
type Secret struct {
	ID                string    `json:"id"`
	Name              string    `json:"name,omitempty"`           // plaintext in-memory (decrypted by App)
	NameLookup        []byte    `json:"name_lookup,omitempty"`    // HMAC-SHA256(key, "passwd.name."+name); DB UNIQUE BLOB
	EncryptedName     []byte    `json:"encrypted_name,omitempty"` // ciphertext BLOB (PackEnvelope)
	Kind              Kind      `json:"kind"`
	EncryptedValue    []byte    `json:"encrypted_value,omitempty"`
	EncryptedOTPSeed  []byte    `json:"encrypted_otp_seed,omitempty"`
	Notes             string    `json:"notes,omitempty"`              // plaintext in-memory
	EncryptedNotes    []byte    `json:"encrypted_notes,omitempty"`    // ciphertext BLOB
	Tags              string    `json:"tags,omitempty"`               // plaintext in-memory
	EncryptedTags     []byte    `json:"encrypted_tags,omitempty"`     // ciphertext BLOB
	Metadata          string    `json:"metadata,omitempty"`           // plaintext in-memory
	EncryptedMetadata []byte    `json:"encrypted_metadata,omitempty"` // ciphertext BLOB
	CreatedAt         time.Time `json:"created_at"`
	UpdatedAt         time.Time `json:"updated_at"`
	// DeletedAt is non-nil when this secret is a tombstone (soft-deleted).
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
}

// NewSecret creates a new Secret with the given parameters.
// id should be a UUID generated by the caller.
// encryptedValue must be ciphertext — never plaintext.
func NewSecret(id, name string, kind Kind, encryptedValue []byte, notes, tags string) Secret {
	now := time.Now().UTC()
	return Secret{
		ID:             id,
		Name:           name,
		Kind:           kind,
		EncryptedValue: encryptedValue,
		Notes:          notes,
		Tags:           tags,
		Metadata:       "",
		CreatedAt:      now,
		UpdatedAt:      now,
	}
}

// OTPAuthRedactedMarker is the placeholder used in metadata when the real OTP
// seed has been moved into EncryptedOTPSeed (issue S-02). Code that needs the
// real secret must read EncryptedOTPSeed and decrypt it with the master key.
const OTPAuthRedactedMarker = "REDACTED"

// PasswordMetadata holds optional metadata for password-type secrets.
// Stored as JSON in the Metadata field alongside other metadata formats.
type PasswordMetadata struct {
	URL         string     `json:"url,omitempty"`
	Username    string     `json:"username,omitempty"`
	OTPAuth     string     `json:"otpauth,omitempty"`
	HOTPCounter uint64     `json:"hotp_counter,omitempty"`
	PwnedCount  int        `json:"pwned_count,omitempty"`
	LastAudited *time.Time `json:"last_audited,omitempty"`
}

// MarshalPasswordMetadata marshals password metadata to a JSON string.
// Returns empty string if all fields are empty.
//
// S-02 hardening: the OTPAuth field is always redacted before serialization
// (the real seed lives in Secret.EncryptedOTPSeed). Callers may pass a URL
// that still has secret=BASE32SECRET — Marshal scrubs it. This is defence in
// depth: even if a future call-site forgets to redact, the seed never lands
// in the plaintext metadata column.
func MarshalPasswordMetadata(meta *PasswordMetadata) string {
	if meta == nil || (meta.URL == "" && meta.Username == "" && meta.OTPAuth == "" && meta.HOTPCounter == 0 && meta.PwnedCount == 0 && (meta.LastAudited == nil || meta.LastAudited.IsZero())) {
		return ""
	}
	scrubbed := *meta
	if scrubbed.OTPAuth != "" {
		scrubbed.OTPAuth = redactOTPAuthSecret(scrubbed.OTPAuth)
	}
	b, err := json.Marshal(&scrubbed)
	if err != nil {
		return ""
	}
	return string(b)
}

// redactOTPAuthSecret rewrites the `secret=` parameter of an otpauth:// URL
// to OTPAuthRedactedMarker. It uses a string-level scan instead of url.Parse
// to avoid pulling otp into secret (which would create an import cycle) and
// to remain forgiving with malformed URIs.
func redactOTPAuthSecret(raw string) string {
	const key = "secret="
	idx := indexOfCaseInsensitive(raw, key)
	if idx < 0 {
		return raw
	}
	start := idx + len(key)
	end := start
	for end < len(raw) && raw[end] != '&' && raw[end] != '#' {
		end++
	}
	// Already redacted? Leave untouched.
	if raw[start:end] == OTPAuthRedactedMarker {
		return raw
	}
	return raw[:start] + OTPAuthRedactedMarker + raw[end:]
}

func indexOfCaseInsensitive(haystack, needle string) int {
	n := len(needle)
	if n == 0 {
		return 0
	}
	for i := 0; i+n <= len(haystack); i++ {
		match := true
		for j := 0; j < n; j++ {
			hc := haystack[i+j]
			nc := needle[j]
			if hc >= 'A' && hc <= 'Z' {
				hc += 'a' - 'A'
			}
			if nc >= 'A' && nc <= 'Z' {
				nc += 'a' - 'A'
			}
			if hc != nc {
				match = false
				break
			}
		}
		if match {
			return i
		}
	}
	return -1
}

// AuditEntry represents a single audit log entry for tracking vault activity.
type AuditEntry struct {
	ID         int       `json:"id"`
	Timestamp  time.Time `json:"timestamp"`
	Action     string    `json:"action"`
	SecretName string    `json:"secret_name"`
	Details    string    `json:"details"`
}

// UnmarshalPasswordMetadata unmarshals password metadata from a JSON string.
// Returns nil if the string is empty or contains no password metadata fields.
func UnmarshalPasswordMetadata(data string) *PasswordMetadata {
	if data == "" {
		return nil
	}
	// First try structured unmarshal
	var meta PasswordMetadata
	if err := json.Unmarshal([]byte(data), &meta); err != nil {
		return nil
	}
	// Check if any fields were populated
	if meta.URL != "" || meta.Username != "" || meta.OTPAuth != "" || meta.HOTPCounter != 0 {
		return &meta
	}
	// Fallback: try generic map for backward compat (old TUI stored "site" key)
	var raw map[string]interface{}
	if err := json.Unmarshal([]byte(data), &raw); err != nil {
		return nil
	}
	if val, ok := raw["username"]; ok {
		if s, ok := val.(string); ok && s != "" {
			meta.Username = s
		}
	}
	if val, ok := raw["site"]; ok {
		if s, ok := val.(string); ok && s != "" {
			meta.URL = s
		}
	}
	if meta.URL != "" || meta.Username != "" || meta.OTPAuth != "" || meta.HOTPCounter != 0 {
		return &meta
	}
	return nil
}
